name: set-envs

on:
  push:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    env:
      REACT_APP_API_KEY: llave
      Key: ${{ secrets.REACT_APP_API_KEY }}
      Llave: Hola

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install and build
        run: npm install && npm run build
      
      - name: Test env
        run: echo "$Llave $Key"

      - name: Deploy
        run: |
          git config --global user.name 'XantX'
          git config --global user.email 'hp_xantx@hotmail.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          npm run deploy
