name: set-envs

on:
  push:
    branches: [ "master" ]

  workflow_dispatch:
env:
  REACT_APP_API_KEY: ${{secrets.REACT_APP_API_KEY}}

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    env:
      key: ${{secrets.REACT_APP_API_KEY}}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install and build
        run: npm install && npm run build
      
      - name: Deploy
        run: |
          echo "$key" 
          git config --global user.name 'XantX'
          git config --global user.email 'hp_xantx@hotmail.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          npm run deploy
