name: set-envs

on:
  push:
    branches: [ "master" ]

  workflow_dispatch:
env:
  REACT_APP_API_KEY: ${{secrets.REACT_APP_API_KEY}}
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Run a one-line script
        run: echo Hello, world!
